apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: stonesoup-int-srvc
rules:
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - internalrequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - internalrequests/finalizers
    verbs:
      - update
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - internalrequests/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - internalservicesconfigs
    verbs:
      - create
      - list
      - watch
      - get
      - patch
      - update
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - internalservicesconfigs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns/status
    verbs:
      - get
