---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: create-advisory
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: advisory
spec:
  description: >-
      Pipeline to push an advisory yaml to a Git repository
  params:
    - name: advisory_json
      type: string
      description: |
          String containing a JSON representation of the advisory data. It should not contain the `advisory`
          top level key (e.g. '{"repo":"myrepo","spec":{"product_id":123,"type":"RHSA"}}')
    - name: application
      type: string
      description: Application being released
    - name: origin
      type: string
      description: |
          The origin workspace where the release CR comes from.
          This is used to determine the advisory path
  tasks:
    - name: create-advisory-task
      taskRef:
        name: create-advisory-task
      params:
        - name: advisory_json
          value: $(params.advisory_json)
        - name: application
          value: $(params.application)
        - name: origin
          value: $(params.origin)
  results:
    - name: result
      value: $(tasks.create-advisory-task.results.result)
