---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: file-updates
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
      Tekton Pipeline to update files in Git repositories
  params:
    - name: upstream_repo
      type: string
      description: Upstream Git repository
    - name: repo
      type: string
      description: Git repository
    - name: ref
      type: string
      description: Git branch
    - name: paths
      type: string
      description: |
          String containing a JSON array of file paths and its replacements
          E.g. '[{"path":"file1.yaml","replacements":[{"key":".yamlkey1,","replacement":"|regex|replace|"}]}]'
  tasks:
    - name: task-process-file-updates
      taskRef:
        name: task-process-file-updates
      params:
        - name: upstream_repo
          value: $(params.upstream_repo)
        - name: repo
          value: $(params.repo)
        - name: ref
          value: $(params.ref)
        - name: paths
          value: $(params.paths)
  results:
    - name: jsonBuildInfo
      value: $(tasks.task-process-file-updates.results.fileUpdatesInfo)
    - name: buildState
      value: $(tasks.task-process-file-updates.results.fileUpdatesState)
